version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: '${devpass}'
    ports:
      - '3306:3306'

  php:
    image: php:7.4.5-apache
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - '8000:80'
    stdin_open: true
    tty: true
